//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxTask1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubDepartment
    {
        public int subdeptid { get; set; }
        public string subdeptname { get; set; }
        public Nullable<int> FKdeptid { get; set; }
    
        public virtual tbl_Department tbl_Department { get; set; }
    }
}
